import { StyleSheet } from "react-native";
const countryDetailStyles = StyleSheet.create({
  countryContainer: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: "black",
  },
  topBar: {
    backgroundColor: "black",
    height: "10%",
    width: "100%",
    top: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-around",
  },
  overlaycolor: {
    position: "absolute",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    opacity: 0.8,
    flex: 1,
    width: "100%",
    height: "100%",
    backgroundColor: "black",
    top: 0,
    bottom: 0,
    zIndex: 9,
  },
  SubTopBar: {
    height: "80%",
    width: "90%",
    backgroundColor: "black",
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  topBarText: {
    color: "white",
    fontSize: 30,
    fontWeight: "bold",
  },
  countryFlag: {
    marginTop: "10%",
    aspectRatio: 3 / 2,
    width: "100%",
    backgroundColor: "white",
  },
  infoContainer: {
    marginTop: "10%",
    marginBottom: "10%",
    display: "flex",
    flexDirection: "column",
    backgroundColor: "black",
    height: "30%",
    width: "80%",
    justifyContent: "space-between",
  },
  fontstyle: {
    fontSize: 15,
    marginLeft: 10,
    color: "white",
  },
  capitalField: {
    height: "30%",
    backgroundColor: "#1F272E",
    borderRadius: 8,
    justifyContent: "center",
  },
  populationField: {
    height: "30%",
    backgroundColor: "#1F272E",
    borderRadius: 8,
    justifyContent: "center",
  },
  latitudeField: {
    height: "30%",
    backgroundColor: "#1F272E",
    borderRadius: 8,
    justifyContent: "center",
  },
});
export default countryDetailStyles;
